package org.example.cooking_recipe_bot.bot.constants;

import lombok.Getter;

@Getter
public enum BotMessageEnum {
    HELLO_MESSAGE,
    HELP_MESSAGE,
    UNKNOWN_USER,
    EXCEPTION_ILLEGAL_MESSAGE,
    EXCEPTION_UPDATE_HANDLE_MESSAGE,
    INSERT_KEYWORD_MESSAGE,
    INSERT_RECIPE_MESSAGE,
    RECIPE_NOT_FOUND_MESSAGE,
    RECIPE_ADDED_MESSAGE,
    RECIPE_PARSING_ERROR,
    RECIPE_ALREADY_EXISTS_MESSAGE,
    RECIPE_SAVING_ERROR,
    RECIPE_SENDING_ERROR,
    RECIPE_UPDATING_FORMAT_ERROR,
    RECIPE_UPDATED_MESSAGE,
    INSERT_NOTIFICATION_MESSAGE,
    CANCEL_MESSAGE,
    USER_NOT_FOUND,
    SEND_ME_PHOTO_MESSAGE,
    SEND_ME_VIDEO_MESSAGE,
    PHOTO_WAS_DELETED_MESSAGE,
    PHOTO_UPDATED_MESSAGE,
    VIDEO_WAS_DELETED_MESSAGE,
    VIDEO_NOT_FOUND_MESSAGE,
    VIDEO_UPDATED_MESSAGE,
    NOTIFICATION_WAS_SENT_MESSAGE,
    USER_WAS_DELETED_MESSAGE,
    USER_WAS_SET_ADMIN_MESSAGE,
    USER_WAS_UNSET_ADMIN_MESSAGE,
    SEND_MORE_RECIPES_QUESTION_MESSAGE,
    RECIPE_NAME_AND_RATING_MESSAGE,
    DELETE_RECIPE_QUESTION_MESSAGE,
    WAITING_FOR_EDITED_RECIPE_MESSAGE,
    AVAILABLE_LANGUAGES_MESSAGE,
    LANGUAGE_WAS_CHANGED_MESSAGE
    ;

}
