package org.example.cooking_recipe_bot.bot.constants;

public enum ButtonNameEnum {
    HELP_BUTTON,
    FIND_RECIPE_BUTTON,
    BREAKFAST_BUTTON,
    LUNCH_BUTTON,
    DINNER_BUTTON,
    FIFTEEN_MIN_BUTTON,
    THIRTY_MIN_BUTTON,
    ADD_RECIPE_BUTTON,
    DELETE_RECIPE_BUTTON,
    FIND_RANDOM_RECIPE_BUTTON,
    USERS_BUTTON,
    SEND_NOTIFICATION,
    MORE_RECIPES,
    CANCEL,
    YES,
    NO,
    OPEN,
    CLOSE,
    DELETE_USER,
    SET_ADMIN,
    UNSET_ADMIN,
    EDIT_RECIPE,
    DELETE_RECIPE,
    CHANGE_PHOTO,
    CHANGE_VIDEO,
    RATE,
    LANGUAGE_RU,
    LANGUAGE_EN

}
